// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/protocol.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DETF_Stream_FullMethodName = "/protocol.DETF/Stream"
)

// DETFClient is the client API for DETF service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DETFClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Result, Match], error)
}

type dETFClient struct {
	cc grpc.ClientConnInterface
}

func NewDETFClient(cc grpc.ClientConnInterface) DETFClient {
	return &dETFClient{cc}
}

func (c *dETFClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Result, Match], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DETF_ServiceDesc.Streams[0], DETF_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Result, Match]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DETF_StreamClient = grpc.BidiStreamingClient[Result, Match]

// DETFServer is the server API for DETF service.
// All implementations must embed UnimplementedDETFServer
// for forward compatibility.
type DETFServer interface {
	Stream(grpc.BidiStreamingServer[Result, Match]) error
	mustEmbedUnimplementedDETFServer()
}

// UnimplementedDETFServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDETFServer struct{}

func (UnimplementedDETFServer) Stream(grpc.BidiStreamingServer[Result, Match]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedDETFServer) mustEmbedUnimplementedDETFServer() {}
func (UnimplementedDETFServer) testEmbeddedByValue()              {}

// UnsafeDETFServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DETFServer will
// result in compilation errors.
type UnsafeDETFServer interface {
	mustEmbedUnimplementedDETFServer()
}

func RegisterDETFServer(s grpc.ServiceRegistrar, srv DETFServer) {
	// If the following call pancis, it indicates UnimplementedDETFServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DETF_ServiceDesc, srv)
}

func _DETF_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DETFServer).Stream(&grpc.GenericServerStream[Result, Match]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DETF_StreamServer = grpc.BidiStreamingServer[Result, Match]

// DETF_ServiceDesc is the grpc.ServiceDesc for DETF service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DETF_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.DETF",
	HandlerType: (*DETFServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _DETF_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/protocol.proto",
}
