// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint64                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_api_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Match) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint64                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Win           bool                   `protobuf:"varint,2,opt,name=Win,proto3" json:"Win,omitempty"`
	Draw          bool                   `protobuf:"varint,3,opt,name=Draw,proto3" json:"Draw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Result) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *Result) GetDraw() bool {
	if x != nil {
		return x.Draw
	}
	return false
}

var File_api_protocol_proto protoreflect.FileDescriptor

const file_api_protocol_proto_rawDesc = "" +
	"\n" +
	"\x12api/protocol.proto\x12\bprotocol\"3\n" +
	"\x05Match\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x04R\x02ID\x12\x1a\n" +
	"\bPosition\x18\x02 \x01(\tR\bPosition\">\n" +
	"\x06Result\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x04R\x02ID\x12\x10\n" +
	"\x03Win\x18\x02 \x01(\bR\x03Win\x12\x12\n" +
	"\x04Draw\x18\x03 \x01(\bR\x04Draw29\n" +
	"\x04DETF\x121\n" +
	"\x06Stream\x12\x10.protocol.Result\x1a\x0f.protocol.Match\"\x00(\x010\x01B\vZ\t/protocolb\x06proto3"

var (
	file_api_protocol_proto_rawDescOnce sync.Once
	file_api_protocol_proto_rawDescData []byte
)

func file_api_protocol_proto_rawDescGZIP() []byte {
	file_api_protocol_proto_rawDescOnce.Do(func() {
		file_api_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protocol_proto_rawDesc), len(file_api_protocol_proto_rawDesc)))
	})
	return file_api_protocol_proto_rawDescData
}

var file_api_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_protocol_proto_goTypes = []any{
	(*Match)(nil),  // 0: protocol.Match
	(*Result)(nil), // 1: protocol.Result
}
var file_api_protocol_proto_depIdxs = []int32{
	1, // 0: protocol.DETF.Stream:input_type -> protocol.Result
	0, // 1: protocol.DETF.Stream:output_type -> protocol.Match
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protocol_proto_init() }
func file_api_protocol_proto_init() {
	if File_api_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protocol_proto_rawDesc), len(file_api_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protocol_proto_goTypes,
		DependencyIndexes: file_api_protocol_proto_depIdxs,
		MessageInfos:      file_api_protocol_proto_msgTypes,
	}.Build()
	File_api_protocol_proto = out.File
	file_api_protocol_proto_goTypes = nil
	file_api_protocol_proto_depIdxs = nil
}
